
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_GPIO_TFT_CONTROL_DEVICE_ID,
		XPAR_AXI_GPIO_TFT_CONTROL_BASEADDR,
		XPAR_AXI_GPIO_TFT_CONTROL_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_TFT_CONTROL_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_TFT_DATA_BUS_DEVICE_ID,
		XPAR_AXI_GPIO_TFT_DATA_BUS_BASEADDR,
		XPAR_AXI_GPIO_TFT_DATA_BUS_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_TFT_DATA_BUS_IS_DUAL
	},
	{
		XPAR_LEDS_DEVICE_ID,
		XPAR_LEDS_BASEADDR,
		XPAR_LEDS_INTERRUPT_PRESENT,
		XPAR_LEDS_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_DEVICE_ID,
		XPAR_PUSH_BUTTONS_BASEADDR,
		XPAR_PUSH_BUTTONS_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_IS_DUAL
	},
	{
		XPAR_SLIDE_SWITCHES_DEVICE_ID,
		XPAR_SLIDE_SWITCHES_BASEADDR,
		XPAR_SLIDE_SWITCHES_INTERRUPT_PRESENT,
		XPAR_SLIDE_SWITCHES_IS_DUAL
	}
};


